### ISSUE TITLE
Error: release "name.v1" already exists

### ISSUE THREAD

**Issue by Legogris** [bmatcuk/helm-take-ownership#2]
For some reason, Tiller/helm has lost knowledge of past releases (they don't show up in `helm list`, but the associated resources are still present in the k8s cluster).

Attempting to use this plugin to resolve the situation, example showing a grafana release:

```
$ helm own --chartname stable/grafana --configmaps grafana --chartversion 1.22.1 --k8s-namespace default --deploy grafana grafana --pods grafana-5f48d98b86-6lfp8 --replicasets grafana-5f48d98b86 --services grafana --debug
2020/05/12 16:42:49 Downloading kubernetes objects...
2020/05/12 16:42:50 Constructing Helm Release...
2020/05/12 16:42:50 Installing Helm Chart...
2020/05/12 16:42:50 creating release %qgrafana.v1
Error: release: "grafana.v1" already exists
```

Tiller version: `v2.14.3`

```
$ helm version
version.BuildInfo{Version:"v3.0", GitCommit:"v3.0.1", GitTreeState:"", GoVersion:"go1.13.6"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"archive", BuildDate:"1970-01-01T00:00:01Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-gke.11", GitCommit:"fd078e6ed95d359cb2c9ca6561754806718c1c98", GitTreeState:"clean", BuildDate:"2020-04-13T20:10:31Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by bmatcuk** [comment]
Hmm, that's strange. It's been a while since I worked on this, so the details are a little fuzzy... but, Helm stores information about releases in a configmap. Sounds to me like those configmaps still exist, but, for some reason, it's not reading them when you issue a `helm list`? If I was you, I'd look into fixing helm - maybe a recent permission change or something is preventing helm from reading the configmaps?

Failing that, if you want to use `helm-take-ownership`, you'll need to remove those configmaps.

**Comment by Legogris** [comment]
The issue seems to be related to using a helm client of version 3 while these were v2 releases. Closing this!

**Comment by bmatcuk** [comment]
Aha! That'd do it =) Glad you got to the bottom of it!
